stack_clone/urls.py
from django.conf.urls import url, include,patterns
from django.contrib import admin
from app.views import ListViewSet, CreationViewSet, UpdateViewSet, DeleteViewSet, DetailsViewSet
from stack_clone import settings

urlpatterns = [
    url(r'^$', 'app.views.homepage', name="homepage"),
    url(r'^admin/', admin.site.urls),
    url(r'^questions/$', ListViewSet.QuestionList.as_view(), name='question-list'),
    url(r'^questions/(?P<pk>[0-9]+)/$', DetailsViewSet.QuestionDetails.as_view(), name='question-details'),
    url(r'^questions/create', CreationViewSet.QuestionCreate.as_view(), name='question-create'),
    url(r'^questions/edit/(?P<pk>[0-9]+)/$', UpdateViewSet.QuestionUpdate.as_view(), name='question-edit'),
    url(r'^questions/delete/(?P<pk>[0-9]+)/$', DeleteViewSet.QuestionDelete.as_view(), name='question-delete'),
    url(r'^questions/(?P<question_id>[0-9]+)/answer/$', 'app.views.create_answer', name='make-answer'),
    url(r'^related_to/(?P<tag>[0-9]+)', 'app.views.related_to', name='related-to'),
    url(r'^register/$', 'app.views.register', name="register"),
    url(r'^login/$', 'app.views.login', name='login'),
    url(r'^logout/$', 'app.views.logout', name='logout'),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_URL}),
    url(r'^about/$', 'app.views.about', name='about-us'),
    url(r'^contact/$', 'app.views.contact', name='contact'),
    url(r'^profile/$', 'app.views.profile', name='profile'),
    url(r'^reset-password/$', 'app.views.change_password', name='password-reset'),
    url(r'^accounts/', include('allauth.urls')),
     url(r'^admin/', include(admin.site.urls)),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Tag(models.Model):
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return '/tags/%s' % (self.id)


class Question(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User)
    updated_at = models.DateTimeField(auto_now=True)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return '/questions/%s' % (self.id)


class Answer(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User)
    is_better = models.BooleanField()
    question = models.ForeignKey(Question)

    def __str__(self):
        return self.content

    def get_absolute_url(self):
        return '/answers/%s' % (self.id)


class Vote(models.Model):
    answer = models.ForeignKey(Answer)
    who = models.ForeignKey(User)
    type = models.CharField(max_length=1)

    def __str__(self):
        res = "%s gave to a %s\'s answer a " % (self.who.username, self.answer.question.title)
        if self.type == 'U':
            res += "+1"
        else:
            res += "-1"
        return res

    def get_absolute_url(self):
        return '/votes/%s' % self.id


class UserProfile(models.Model):
    user = models.OneToOneField(User)
    avatar = models.ImageField()

app/forms.py
from django.contrib.auth.models import User
from django.forms import ModelForm, CharField, PasswordInput
# from django.utils.translation import ugettext, ugettext_lazy as _

class RegistrationForm(ModelForm):

    password1 = CharField(widget=PasswordInput)
    password2 = CharField(widget=PasswordInput, help_text="Enter the same password as before, for verification.")

    class Meta:
        model = User
        fields = ("username","email", "first_name", "last_name",)

app/views.py
from django.contrib import auth
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse_lazy, reverse
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, render_to_response
from django.template import RequestContext
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from app.models import Question, Answer, Tag


def homepage(request):
    return render(request, 'app/default/index.html')


class ListViewSet:
    class QuestionList(ListView):
        model = Question
        template_name = "app/question/list.html"
        context_object_name = "questions"


class DetailsViewSet:
    class QuestionDetails(DetailView):
        model = Question
        template_name = "app/question/details.html"
        context_object_name = "question"


class CreationViewSet:
    class QuestionCreate(CreateView):
        model = Question
        fields = ['title', 'content', 'tags']
        template_name = 'app/question/create.html'
        success_url = reverse_lazy('question-list')


class UpdateViewSet:
    class QuestionUpdate(UpdateView):
        model = Question
        fields = ['title', 'content', 'author', 'tags']
        template_name = 'app/question/create.html'
        success_url = reverse_lazy('question-list')


class DeleteViewSet:
    class QuestionDelete(DeleteView):
        model = Question
        success_url = reverse_lazy('question-list')
        template_name = 'app/question/delete.html'


def create_answer(request, question_id):
    ans = Answer()
    ans.question = Question.objects.get(pk=question_id)
    ans.author = request.user
    ans.content = request.POST['content']
    ans.is_better = False
    ans.save()
    return HttpResponseRedirect(reverse('question-details', args=(question_id,)))


def related_to(request, tag):
    tag_res = get_object_or_404(Tag, pk=tag)
    res = tag_res.question_set.all()
    return render(request, 'app/question/related.html', {'questions': res, 'tag_name': tag_res})


def register(request):
    errors = []
    if request.method == 'POST':
        user = User()
        user.username = request.POST['username']
        user.email = request.POST['email']
        user.first_name = request.POST['first_name']
        user.last_name = request.POST['last_name']

        password = request.POST['password']
        password_confirmation = request.POST['password2']
        if password == password_confirmation:
            user.set_password(password)
            user.save()
            return HttpResponseRedirect(reverse('homepage'))
        else:
            errors.append("The password didn't match")
            return HttpResponseRedirect(reverse('register'))
    else:
        return render(request, 'app/auth/register.html', {'errors': errors},
                      context_instance=RequestContext(request))


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        access = authenticate(username=username, password=password)
        if access is not None:
            if access.is_active:
                auth.login(request, access)
                return HttpResponseRedirect(reverse('homepage'))
            else:
                return render_to_response('app/auth/inactive.html')
        else:
            return render_to_response('app/auth/nouser.html')
    else:
        return render(request, 'app/auth/login.html')


@login_required
def profile(request):
    user = request.user
    if request.method == "POST":
        user.username = request.POST['username']
        user.first_name = request.POST['first_name']
        user.last_name = request.POST['last_name']
        user.email = request.POST['email']
        user.save()
        return HttpResponseRedirect(reverse('profile'))
    return render(request, 'app/auth/profile.html', {'user': user})


def change_password(request):
    user = request.user
    password = request.POST['password']
    password1 = request.POST['password1']
    if password == password1:
        user.set_password(password)
        return HttpResponseRedirect(reverse('profile'))


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('homepage'))


def about(request):
    return render(request, 'app/default/about.html')


def contact(request):
    return render(request, 'app/default/contact.html')

templates/app/default/about.html
{% extends 'base.html' %}
{% block title %}About us{% endblock %}
{% block body %}
    <h1>About us</h1>
{% endblock %}

templates/app/default/contact.html
{% extends 'base.html' %}
{% block title %}Contact us{% endblock %}
{% block body %}
    <h1>Contact</h1>
{% endblock %}

templates/app/default/index.html
{% extends 'base.html' %}
{% block title %}Homepage{% endblock %}
{% load staticfiles %}
{% block level_styles %}
    <link rel="stylesheet" href="{% static 'modules/homepage/css/carousel.css' %}">
{% endblock %}
{% block body %}
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class=""></li>
            <li data-target="#myCarousel" data-slide-to="1" class=""></li>
            <li data-target="#myCarousel" data-slide-to="2" class="active"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <div class="item">
                <img class="first-slide"
                     src="{% static 'img/banner1.jpg' %}"
                     alt="First slide">
                <div class="container">
                    <div class="carousel-caption">
                        <h1>Example headline.</h1>
                        <p>Note: If you're viewing this page via a <code>file://</code> URL, the "next" and "previous"
                            Glyphicon buttons on the left and right might not load/display properly due to web browser
                            security rules.</p>
                        <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
                    </div>
                </div>
            </div>
            <div class="item">
                <img class="second-slide"
                     src="{% static 'img/banner2.jpg' %}"
                     alt="Second slide">
                <div class="container">
                    <div class="carousel-caption">
                        <h1>Another example headline.</h1>
                        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta
                            gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                        <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
                    </div>
                </div>
            </div>
            <div class="item active">
                <img class="third-slide"
                     src="{% static 'img/banner3.jpg' %}"
                     alt="Third slide">
                <div class="container">
                    <div class="carousel-caption">
                        <h1>One more for good measure.</h1>
                        <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta
                            gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                        <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
                    </div>
                </div>
            </div>
        </div>
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <div class="container marketing">

        <!-- Three columns of text below the carousel -->
        <div class="row">
            <div class="col-lg-4">
                <img class="img-circle"
                     src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="
                     alt="Generic placeholder image" width="140" height="140">
                <h2>Heading</h2>
                <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies
                    vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo
                    cursus magna.</p>
                <p><a class="btn btn-default" href="#" role="button">View details »</a></p>
            </div><!-- /.col-lg-4 -->
            <div class="col-lg-4">
                <img class="img-circle"
                     src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="
                     alt="Generic placeholder image" width="140" height="140">
                <h2>Heading</h2>
                <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras
                    mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris
                    condimentum nibh.</p>
                <p><a class="btn btn-default" href="#" role="button">View details »</a></p>
            </div><!-- /.col-lg-4 -->
            <div class="col-lg-4">
                <img class="img-circle"
                     src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw=="
                     alt="Generic placeholder image" width="140" height="140">
                <h2>Heading</h2>
                <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula
                    porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh,
                    ut fermentum massa justo sit amet risus.</p>
                <p><a class="btn btn-default" href="#" role="button">View details »</a></p>
            </div><!-- /.col-lg-4 -->
        </div><!-- /.row -->


        <!-- START THE FEATURETTES -->

        <hr class="featurette-divider">

        <div class="row featurette">
            <div class="col-md-7">
                <h2 class="featurette-heading">First featurette heading. <span
                        class="text-muted">It'll blow your mind.</span></h2>
                <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis
                    euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus,
                    tellus ac cursus commodo.</p>
            </div>
            <div class="col-md-5">
                <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto"
                     alt="500x500"
                     src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNTAwIiBoZWlnaHQ9IjUwMCIgdmlld0JveD0iMCAwIDUwMCA1MDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjwhLS0KU291cmNlIFVSTDogaG9sZGVyLmpzLzUwMHg1MDAvYXV0bwpDcmVhdGVkIHdpdGggSG9sZGVyLmpzIDIuNi4wLgpMZWFybiBtb3JlIGF0IGh0dHA6Ly9ob2xkZXJqcy5jb20KKGMpIDIwMTItMjAxNSBJdmFuIE1hbG9waW5za3kgLSBodHRwOi8vaW1za3kuY28KLS0+PGRlZnM+PHN0eWxlIHR5cGU9InRleHQvY3NzIj48IVtDREFUQVsjaG9sZGVyXzE1NGJiYWYzZmIwIHRleHQgeyBmaWxsOiNBQUFBQUE7Zm9udC13ZWlnaHQ6Ym9sZDtmb250LWZhbWlseTpBcmlhbCwgSGVsdmV0aWNhLCBPcGVuIFNhbnMsIHNhbnMtc2VyaWYsIG1vbm9zcGFjZTtmb250LXNpemU6MjVwdCB9IF1dPjwvc3R5bGU+PC9kZWZzPjxnIGlkPSJob2xkZXJfMTU0YmJhZjNmYjAiPjxyZWN0IHdpZHRoPSI1MDAiIGhlaWdodD0iNTAwIiBmaWxsPSIjRUVFRUVFIi8+PGc+PHRleHQgeD0iMTg1LjEyNSIgeT0iMjYxLjEiPjUwMHg1MDA8L3RleHQ+PC9nPjwvZz48L3N2Zz4="
                     data-holder-rendered="true">
            </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette">
            <div class="col-md-7 col-md-push-5">
                <h2 class="featurette-heading">Oh yeah, it's that good. <span
                        class="text-muted">See for yourself.</span></h2>
                <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis
                    euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus,
                    tellus ac cursus commodo.</p>
            </div>
            <div class="col-md-5 col-md-pull-7">
                <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto"
                     alt="500x500"
                     src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNTAwIiBoZWlnaHQ9IjUwMCIgdmlld0JveD0iMCAwIDUwMCA1MDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjwhLS0KU291cmNlIFVSTDogaG9sZGVyLmpzLzUwMHg1MDAvYXV0bwpDcmVhdGVkIHdpdGggSG9sZGVyLmpzIDIuNi4wLgpMZWFybiBtb3JlIGF0IGh0dHA6Ly9ob2xkZXJqcy5jb20KKGMpIDIwMTItMjAxNSBJdmFuIE1hbG9waW5za3kgLSBodHRwOi8vaW1za3kuY28KLS0+PGRlZnM+PHN0eWxlIHR5cGU9InRleHQvY3NzIj48IVtDREFUQVsjaG9sZGVyXzE1NGJiYWYwMTNkIHRleHQgeyBmaWxsOiNBQUFBQUE7Zm9udC13ZWlnaHQ6Ym9sZDtmb250LWZhbWlseTpBcmlhbCwgSGVsdmV0aWNhLCBPcGVuIFNhbnMsIHNhbnMtc2VyaWYsIG1vbm9zcGFjZTtmb250LXNpemU6MjVwdCB9IF1dPjwvc3R5bGU+PC9kZWZzPjxnIGlkPSJob2xkZXJfMTU0YmJhZjAxM2QiPjxyZWN0IHdpZHRoPSI1MDAiIGhlaWdodD0iNTAwIiBmaWxsPSIjRUVFRUVFIi8+PGc+PHRleHQgeD0iMTg1LjEyNSIgeT0iMjYxLjEiPjUwMHg1MDA8L3RleHQ+PC9nPjwvZz48L3N2Zz4="
                     data-holder-rendered="true">
            </div>
        </div>

        <hr class="featurette-divider">

        <div class="row featurette">
            <div class="col-md-7">
                <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
                <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis
                    euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus,
                    tellus ac cursus commodo.</p>
            </div>
            <div class="col-md-5">
                <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto"
                     alt="500x500"
                     src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iNTAwIiBoZWlnaHQ9IjUwMCIgdmlld0JveD0iMCAwIDUwMCA1MDAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjwhLS0KU291cmNlIFVSTDogaG9sZGVyLmpzLzUwMHg1MDAvYXV0bwpDcmVhdGVkIHdpdGggSG9sZGVyLmpzIDIuNi4wLgpMZWFybiBtb3JlIGF0IGh0dHA6Ly9ob2xkZXJqcy5jb20KKGMpIDIwMTItMjAxNSBJdmFuIE1hbG9waW5za3kgLSBodHRwOi8vaW1za3kuY28KLS0+PGRlZnM+PHN0eWxlIHR5cGU9InRleHQvY3NzIj48IVtDREFUQVsjaG9sZGVyXzE1NGJiYWYwNDAxIHRleHQgeyBmaWxsOiNBQUFBQUE7Zm9udC13ZWlnaHQ6Ym9sZDtmb250LWZhbWlseTpBcmlhbCwgSGVsdmV0aWNhLCBPcGVuIFNhbnMsIHNhbnMtc2VyaWYsIG1vbm9zcGFjZTtmb250LXNpemU6MjVwdCB9IF1dPjwvc3R5bGU+PC9kZWZzPjxnIGlkPSJob2xkZXJfMTU0YmJhZjA0MDEiPjxyZWN0IHdpZHRoPSI1MDAiIGhlaWdodD0iNTAwIiBmaWxsPSIjRUVFRUVFIi8+PGc+PHRleHQgeD0iMTg1LjEyNSIgeT0iMjYxLjEiPjUwMHg1MDA8L3RleHQ+PC9nPjwvZz48L3N2Zz4="
                     data-holder-rendered="true">
            </div>
        </div>

        <hr class="featurette-divider">

        <!-- /END THE FEATURETTES -->


        <!-- FOOTER -->
        <footer>
            <p class="pull-right"><a href="#">Back to top</a></p>
            <p>© 2015 Company, Inc. · <a href="#">Privacy</a> · <a href="#">Terms</a></p>
        </footer>

    </div>
{% endblock %}

templates/app/question/create.html
{% extends 'base.html' %}
{% block title %}Make a question{% endblock %}

{% block body %}
    {% if form.errors %}
        <p style="color: red;">
            Por favor corrige lo siguiente: </p>
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        <div class="field">
            {{ form.title.errors }}
            <label for="id_title">Title:</label> {{ form.title }}
        </div>
        <div class="field">
            {{ form.content.errors }}
            <label for="id_content">Content:</label> {{ form.content }}
        </div>
        <div class="field">
            {{ form.author.errors }}
            <label for="id_author">Author:</label> {{ form.author }}
        </div>
        <div class="field">
            {{ form.tags.errors }}
            <label for="id_tags">Author:</label> {{ form.tags }}
        </div>
        <input type="submit" value="Enviar">
    </form>
{% endblock %}

templates/app/question/delete.html
{% extends 'base.html' %}
{% block title %}Delete confirmation{% endblock %}
{% block body %}
    <form action="" method="post">{% csrf_token %}
        <p> ¿Realmente quieres borrar este {{ object }}"?</p>
        <input type="submit" value="Confirmar"/>
    </form>
{% endblock %}

templates/question_layout.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}{{ question }}{% endblock %}
{% block level_styles %}

    <link rel="stylesheet" href="{% static 'modules/questions/details.css' %}">
    <link rel="stylesheet" href="{% static 'modules/questions/list.css' %}">
{% endblock %}
{% block body %}
    {#    <a href="{% url 'question-list' %}">Back to all questions</a>#}
    {#    <h1>{{ question }}</h1>#}
    {#    <p>{{ question.content }}</p>#}
    {#    {% if question.answer_set %}#}
    {#        <ul>#}
    {#            {% for answer in question.answer_set.all %}#}
    {#                <li>{{ answer }}</li>#}
    {#            {% endfor %}#}
    {#        </ul>#}
    {#    {% else %}#}
    {#        <h1>Sin respuestas o comentarios, prueba a ser el primero</h1>#}
    {#    {% endif %}#}
    {##}
    {#    <form action="{% url 'make-answer' question.pk %}" method="POST">#}
    {#        {% csrf_token %}#}
    {#        <textarea name="content"></textarea>#}
    {#        <input type="submit" value="Comment">#}
    {#    </form>#}

    <section class="container main-content">
        <div class="row">
            {% block content %}
            {% endblock %}
            <aside class="col-md-3 sidebar">
                <div class="widget widget_stats">
                    <h3 class="widget_title">Stats</h3>
                    <div class="ul_list ul_list-icon-ok">
                        <ul>
                            <li><i class="glyphicon glyphicon-question-sign"></i> Questions ( <span>20</span> )</li>
                            <li><i class="glyphicon glyphicon-comment"></i> Answers ( <span>50</span> )</li>
                        </ul>
                    </div>
                </div>

                <div class="widget widget_social">
                    <h3 class="widget_title">Find Us</h3>
                    <ul>
                        <li class="rss-subscribers">
                            <a href="#" target="_blank">
                                <strong>
                                    <i class="fa fa-rss"></i>
                                    <span>Subscribe</span><br>
                                    <small>To RSS Feed</small>
                                </strong>
                            </a>
                        </li>
                        <li class="facebook-fans">
                            <a href="#" target="_blank">
                                <strong>
                                    <i class="fa fa-facebook"></i>
                                    <span>5,000</span><br>
                                    <small>People like it</small>
                                </strong>
                            </a>
                        </li>
                        <li class="twitter-followers">
                            <a href="#" target="_blank">
                                <strong>
                                    <i class="fa fa-twitter"></i>
                                    <span>3,000</span><br>
                                    <small>Followers</small>
                                </strong>
                            </a>
                        </li>
                        <li class="youtube-subs">
                            <a href="#" target="_blank">
                                <strong>
                                    <i class="fa fa-youtube"></i>
                                    <span>1,000</span><br>
                                    <small>Subscribers</small>
                                </strong>
                            </a>
                        </li>
                    </ul>
                </div>

                <section class="highest-points widget">
                    <div class="highest-content ">
                        <h3>Highest Points</h3>
                        <ul>
                            <li>
                                <div class="img-author">
                                    <img src="{% static 'img/default-avatar.png' %}" width="65" height="65"
                                         class="img-thumbnail img-circle img-responsive" alt="">
                                </div>
                                <div class="details-author">
                                    <h6><a href="">nombre</a></h6>
                                    <span>12 puntos</span>
                                </div>
                            </li>
                            <li>
                                <div class="img-author">
                                    <img src="{% static 'img/default-avatar.png' %}" width="65" height="65"
                                         class="img-thumbnail img-circle img-responsive" alt="">
                                </div>
                                <div class="details-author">
                                    <h6><a href="">nombre</a></h6>
                                    <span>12 puntos</span>
                                </div>
                            </li>
                            <li>
                                <div class="img-author">
                                    <img src="{% static 'img/default-avatar.png' %}" width="65" height="65"
                                         class="img-thumbnail img-circle img-responsive" alt="">
                                </div>
                                <div class="details-author">
                                    <h6><a href="">nombre</a></h6>
                                    <span>12 puntos</span>
                                </div>
                            </li>
                        </ul>
                    </div>
                </section>

                <div class="widget widget_tag_cloud">
                    <h3 class="widget_title">Tags</h3>
                    <a href="#">projects</a>
                    <a href="#">Portfolio</a>
                    <a href="#">Wordpress</a>
                    <a href="#">Html</a>
                    <a href="#">Css</a>
                    <a href="#">jQuery</a>
                    <a href="#">2code</a>
                    <a href="#">vbegy</a>
                </div>

                <div class="widget">
                    <h3 class="widget_title">Recent Questions</h3>
                    <ul class="related-posts">
                        <li class="related-item">
                            <h3><a href="#">This is my first Question</a></h3>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                            <div class="clear"></div>
                            <span>Feb 22, 2014</span>
                        </li>
                        <li class="related-item">
                            <h3><a href="#">This Is My Second Poll Question</a></h3>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                            <div class="clear"></div>
                            <span>Feb 22, 2014</span>
                        </li>
                    </ul>
                </div>

            </aside><!-- End sidebar -->
        </div>
    </section>

{% endblock %}